// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Gimela.Tasks.Triggers.Trigger.#Fire()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Gimela.Tasks.Triggers.Trigger.#Run()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Gimela.Common.Logging.Logger.Debug(System.String)", Scope = "member", Target = "Gimela.Tasks.Triggers.CronTrigger.#CheckContinue()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Gimela.Common.Logging.Logger.Debug(System.String)", Scope = "member", Target = "Gimela.Tasks.Triggers.CronTrigger.#ComputeNextFireTime()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Gimela.Common.Logging.Logger.Debug(System.String)", Scope = "member", Target = "Gimela.Tasks.Triggers.CronTrigger.#WaitingMilliseconds")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Gimela.Common.Logging.Logger.Debug(System.String)", Scope = "member", Target = "Gimela.Tasks.Triggers.OnceTrigger.#CheckFireTime()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Gimela.Common.Logging.Logger.Debug(System.String)", Scope = "member", Target = "Gimela.Tasks.Triggers.OnceTrigger.#WaitingMilliseconds")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ParseExpression(System.String,System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ValidateCronExpression(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpression.#CronExpressionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ValidateCronExpression(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "member", Target = "Gimela.Tasks.Triggers.CronTrigger.#CronExpression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "member", Target = "Gimela.Tasks.Triggers.CronTrigger.#CronExpressionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "type", Target = "Gimela.Tasks.Expressions.CronExpression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "type", Target = "Gimela.Tasks.Expressions.CronExpressionCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "type", Target = "Gimela.Tasks.Expressions.CronExpressionHelper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "type", Target = "Gimela.Tasks.Expressions.CronExpressionValidationException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cron", Scope = "type", Target = "Gimela.Tasks.Triggers.CronTrigger")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "cron", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpression.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "param", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionValidationException.#.ctor(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "param", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionValidationException.#Throw(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "cron", Scope = "member", Target = "Gimela.Tasks.Triggers.CronTrigger.#.ctor(System.String,Gimela.Tasks.IJob)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Stop", Scope = "member", Target = "Gimela.Tasks.IScheduleTask.#Stop()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpression.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "Gimela.Tasks.Triggers.CronTrigger.#.ctor(System.String,Gimela.Tasks.IJob)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Gimela.Tasks.ScheduleTaskCollection.#Clear()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Gimela.Tasks.ScheduleTaskCollection.#Collection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Gimela.Tasks.ScheduleTaskCollection.#Remove(Gimela.Tasks.IScheduleTask)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2105:ArrayFieldsShouldNotBeReadOnly", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ValidChars")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2105:ArrayFieldsShouldNotBeReadOnly", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ValidNumberChars")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2105:ArrayFieldsShouldNotBeReadOnly", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ValidSpecialChars")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CronExpression", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ValidateCronExpression(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CronExpression", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpression.#BuildExpression()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CronExpression", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionValidationException.#.ctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CronExpressionString", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpression.#BuildExpression()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CronExpressionString", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpression.#CronExpressionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "splitted", Scope = "member", Target = "Gimela.Tasks.Expressions.CronExpressionHelper.#ParseExpression(System.String,System.String,System.Int32,System.Int32)")]
